### ISSUE TITLE
IPFS vacuum cleanup

### ISSUE THREAD

**Issue by aahutsal** [acolytec3/signpost#2]
Once IPFS performs garbage collection your digital asset under NFT might dissaper.
What about replacing NFT with Arweave which is permaweb, @acolytec3?

**Comment by acolytec3** [comment]
It certainly could be done. That said, this was a hackathon project and there isn't any any easy solution at this point for a user acquiring AR and paying for the storage fees.  

That's why the readme suggests creating an account with Pinata and securing your metadata that way.

**Comment by aahutsal** [comment]
Got you. Closing that issue then.
